services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  mongo:
    image: mongo:latest
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: 123
      MONGO_DATABASE: database
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  mongo_data:
    driver: local
